nodeLinker: node-modules

packageExtensions:
  "@nrwl/devkit@*":
    dependencies:
      "nx": ^19.4.2
  "cosmiconfig-typescript-loader@*":
    dependencies:
      "@types/node": ^20.14.10
      "typescript": ^5.5.3
  "eslint-plugin-i@*":
    peerDependencies:
      "eslint": ^9.0.0

yarnPath: .yarn/releases/yarn-4.5.0.cjs
