[package]
name = "identity"
description = "Identity and Access Management service"
authors = ["Dmitriy Chukhno <dmitr1sdadaya@protonmail.com>"]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[[bin]]
path = "src/main.rs"
name = "identity"

[dependencies]
# Asynchronous and Streams
tokio = { version = "1.35.1", features = ["full"] }
tokio-stream = "0.1.14"
futures = "0.3.30"
async-trait = "0.1.75"

# Web Framework (Axum)
axum = { version = "0.7.5", features = [
  "http2",
  "json",
  "form",
  "multipart",
  "query",
  "ws",
  "macros",
] }
axum-prometheus = "0.6.1"

# Middleware + Utilities
tower-http = { version = "0.5.0", features = [
  "trace",
  "cors",
  "sensitive-headers",
  "fs",
  "compression-zstd",
  "compression-gzip",
  "compression-deflate",
  "compression-br",
] }
tower = "0.4.13"

# Tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# gRPC
tonic = "0.11.0"
prost-types = "0.12.3"
prost = "0.12.3"

# Serialization/Deserialization
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.26", features = ["serde"] }

# Security and Cryptography
sha2 = "0.10.8"
hmac = "0.12.1"
argon2 = { version = "0.5.0", features = ["std"] }
totp-rs = { version = "5.0.2", features = ["gen_secret"] }

# Random Number Generation
rand = "0.8.5"
rand_chacha = "0.3.1"

# Byte and Encoding Utilities
bytes = "1.4.0"
base64-url = "3.0.0"
hex = "0.4.3"

# Database Management
sqlx = { version = "0.7.4", features = [
  "runtime-tokio-rustls",
  "postgres",
  "chrono",
  "macros",
  "migrate",
  "rust_decimal",
  "json",
] }

# Validation and Error Handling
validator = { version = "0.18.0", features = ["derive"] }
thiserror = "1.0.56"
regex = "1.8.4"

# Utilities
bitflags = "2.4.0"
jemallocator = "0.5.4"

# Cloud Storage
rust-s3 = "0.34.0"

# Local Dependencies
id = { path = "../../packages/id-rs" }

[build-dependencies]
tonic-build = "0.11.0"
